/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lison_jnicallbackdemo_JniCall */

#ifndef _Included_com_lison_jnicallbackdemo_JniCall
#define _Included_com_lison_jnicallbackdemo_JniCall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lison_jnicallbackdemo_JniCall
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lison_jnicallbackdemo_JniCall_start
  (JNIEnv *, jobject);

/*
 * Class:     com_lison_jnicallbackdemo_JniCall
 * Method:    mainThread
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lison_jnicallbackdemo_JniCall_mainThread
  (JNIEnv *, jobject);

/*
 * Class:     com_lison_jnicallbackdemo_JniCall
 * Method:    setJNIEnv
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lison_jnicallbackdemo_JniCall_setJNIEnv
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
